"""All ORM models. Importing this module registers every table on ``Base``."""

from draftgpt.database.models.base import Base, ProvenanceMixin, TimestampMixin, new_id, utcnow
from draftgpt.database.models.draft import (
    AdpSnapshot,
    Draft,
    DraftPick,
    DraftSlot,
    DraftStateVersion,
)
from draftgpt.database.models.league import (
    League,
    LeagueRules,
    LeagueSeason,
    Matchup,
    PulseAcknowledgement,
    RosterMembership,
    RosterSlot,
    StandingsSnapshot,
    Team,
    TeamSeason,
    Transaction,
    User,
    WaiverStateSnapshot,
)
from draftgpt.database.models.market import MarketTrend, Projection, Ranking, Tier
from draftgpt.database.models.player import (
    DepthChartSnapshot,
    MarketContextSnapshot,
    NewsItem,
    NflGame,
    NflTeam,
    Player,
    PlayerAlias,
    PlayerProviderId,
    PlayerSeasonEligibility,
    PlayerStatusEvent,
    UsageSnapshot,
    WeatherSnapshot,
)
from draftgpt.database.models.recommendation import (
    DecisionSnapshot,
    PulseItem,
    PulseRun,
    RecommendationCandidate,
    RecommendationRun,
)
from draftgpt.database.models.source import (
    IngestionRun,
    ManualOverride,
    SourceFreshness,
    SourceProvider,
)

__all__ = [
    "AdpSnapshot",
    "Base",
    "DecisionSnapshot",
    "DepthChartSnapshot",
    "Draft",
    "DraftPick",
    "DraftSlot",
    "DraftStateVersion",
    "IngestionRun",
    "League",
    "LeagueRules",
    "LeagueSeason",
    "ManualOverride",
    "MarketContextSnapshot",
    "MarketTrend",
    "Matchup",
    "NewsItem",
    "NflGame",
    "NflTeam",
    "Player",
    "PlayerAlias",
    "PlayerProviderId",
    "PlayerSeasonEligibility",
    "PlayerStatusEvent",
    "Projection",
    "ProvenanceMixin",
    "PulseAcknowledgement",
    "PulseItem",
    "PulseRun",
    "Ranking",
    "RecommendationCandidate",
    "RecommendationRun",
    "RosterMembership",
    "RosterSlot",
    "SourceFreshness",
    "SourceProvider",
    "StandingsSnapshot",
    "Team",
    "TeamSeason",
    "Tier",
    "TimestampMixin",
    "Transaction",
    "UsageSnapshot",
    "User",
    "WaiverStateSnapshot",
    "WeatherSnapshot",
    "new_id",
    "utcnow",
]
