"""initial schema

Revision ID: 1913b6aabc8e
Revises: 
Create Date: 2026-08-13 22:44:45.729606
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1913b6aabc8e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('format', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('provider_key', 'external_id', name='uq_leagues_provider_key')
    )
    op.create_table('manual_overrides',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_table', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_overrides'))
    )
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_overrides_entity_id'), ['entity_id'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_items')),
    sa.UniqueConstraint('provider_key', 'external_id', name='uq_news_items_provider_key')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_provider_id'), ['provider_id'], unique=False)

    op.create_table('nfl_teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('conference', sa.String(length=4), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.Column('bye_week_by_season', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nfl_teams')),
    sa.UniqueConstraint('abbreviation', name='uq_nfl_teams_abbreviation')
    )
    op.create_table('source_providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('freshness_class', sa.String(length=16), nullable=False),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('raw_retention_days', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_providers')),
    sa.UniqueConstraint('key', name='uq_source_providers_key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('risk_preference', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('handle', name='uq_users_handle')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['source_providers.id'], name=op.f('fk_ingestion_runs_provider_id_source_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_ingestion_runs_idempotency_key')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_provider_id'), ['provider_id'], unique=False)

    op.create_table('league_seasons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('regular_season_weeks', sa.Integer(), nullable=False),
    sa.Column('playoff_weeks', sa.JSON(), nullable=False),
    sa.Column('playoff_team_count', sa.Integer(), nullable=True),
    sa.Column('trade_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_league_seasons_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_seasons')),
    sa.UniqueConstraint('league_id', 'season', name='uq_league_seasons_league_id')
    )
    with op.batch_alter_table('league_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_seasons_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_seasons_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_seasons_provider_id'), ['provider_id'], unique=False)

    op.create_table('nfl_games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.String(length=32), nullable=False),
    sa.Column('away_team_id', sa.String(length=32), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('is_dome', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['nfl_teams.id'], name=op.f('fk_nfl_games_away_team_id_nfl_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['nfl_teams.id'], name=op.f('fk_nfl_games_home_team_id_nfl_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nfl_games')),
    sa.UniqueConstraint('season', 'week', 'home_team_id', name='uq_nfl_games_season')
    )
    with op.batch_alter_table('nfl_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfl_games_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfl_games_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_nfl_games_season_week', ['season', 'week'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('primary_position', sa.String(length=8), nullable=False),
    sa.Column('nfl_team_id', sa.String(length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_team_defense', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_team_id'], ['nfl_teams.id'], name=op.f('fk_players_nfl_team_id_nfl_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index('ix_players_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_provider_id'), ['provider_id'], unique=False)

    op.create_table('source_freshness',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('freshness_class', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['source_providers.id'], name=op.f('fk_source_freshness_provider_id_source_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_freshness')),
    sa.UniqueConstraint('provider_id', 'capability', 'scope', name='uq_source_freshness_provider_id')
    )
    with op.batch_alter_table('source_freshness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_freshness_provider_id'), ['provider_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('is_owner_team', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_teams_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('league_id', 'external_id', name='uq_teams_league_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_league_id'), ['league_id'], unique=False)

    op.create_table('adp_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=False),
    sa.Column('adp_stdev', sa.Float(), nullable=True),
    sa.Column('earliest_pick', sa.Integer(), nullable=True),
    sa.Column('latest_pick', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_adp_snapshots_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adp_snapshots')),
    sa.UniqueConstraint('player_id', 'season', 'provider_id', 'retrieved_at', name='uq_adp_snapshots_player_id')
    )
    with op.batch_alter_table('adp_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adp_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('decision_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=True),
    sa.Column('league_rules_id', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_versions', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_decision_snapshots_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_snapshots'))
    )
    with op.batch_alter_table('decision_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_decision_snapshots_league_time', ['league_season_id', 'created_at'], unique=False)

    op.create_table('depth_chart_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nfl_team_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_team_id'], ['nfl_teams.id'], name=op.f('fk_depth_chart_snapshots_nfl_team_id_nfl_teams')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_depth_chart_snapshots_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depth_chart_snapshots'))
    )
    with op.batch_alter_table('depth_chart_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depth_chart_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_chart_snapshots_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_depth_chart_snapshots_team_eff', ['nfl_team_id', 'season', 'week'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('seconds_per_pick', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_drafts_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts')),
    sa.UniqueConstraint('league_season_id', name='uq_drafts_league_season_id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_provider_id'), ['provider_id'], unique=False)

    op.create_table('league_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scoring', sa.JSON(), nullable=False),
    sa.Column('waiver_type', sa.String(length=24), nullable=False),
    sa.Column('faab_budget', sa.Integer(), nullable=True),
    sa.Column('waiver_process_days', sa.JSON(), nullable=False),
    sa.Column('waiver_tiebreak', sa.String(length=48), nullable=True),
    sa.Column('roster_size', sa.Integer(), nullable=True),
    sa.Column('ir_slots', sa.Integer(), nullable=False),
    sa.Column('trade_review_type', sa.String(length=24), nullable=True),
    sa.Column('raw_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_league_rules_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_rules')),
    sa.UniqueConstraint('league_season_id', 'version', name='uq_league_rules_league_season_id')
    )
    with op.batch_alter_table('league_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_rules_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_rules_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_rules_provider_id'), ['provider_id'], unique=False)

    op.create_table('market_context_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nfl_game_id', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('home_spread', sa.Float(), nullable=True),
    sa.Column('home_implied_total', sa.Float(), nullable=True),
    sa.Column('away_implied_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_game_id'], ['nfl_games.id'], name=op.f('fk_market_context_snapshots_nfl_game_id_nfl_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_context_snapshots'))
    )
    with op.batch_alter_table('market_context_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_context_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_context_snapshots_nfl_game_id'), ['nfl_game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_context_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('market_trends',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('rostered_pct', sa.Float(), nullable=True),
    sa.Column('started_pct', sa.Float(), nullable=True),
    sa.Column('adds_24h', sa.Integer(), nullable=True),
    sa.Column('drops_24h', sa.Integer(), nullable=True),
    sa.Column('rostered_pct_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_market_trends_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_trends')),
    sa.UniqueConstraint('player_id', 'season', 'week', 'provider_id', 'retrieved_at', name='uq_market_trends_player_id')
    )
    with op.batch_alter_table('market_trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_trends_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trends_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trends_provider_id'), ['provider_id'], unique=False)

    op.create_table('player_aliases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('normalized_alias', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_aliases_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_aliases')),
    sa.UniqueConstraint('normalized_alias', 'player_id', name='uq_player_aliases_normalized_alias')
    )
    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_aliases_normalized_alias'), ['normalized_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_aliases_player_id'), ['player_id'], unique=False)

    op.create_table('player_provider_ids',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_name', sa.String(length=128), nullable=True),
    sa.Column('match_method', sa.String(length=24), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_provider_ids_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_provider_ids')),
    sa.UniqueConstraint('provider_key', 'external_id', name='uq_player_provider_ids_provider_key')
    )
    with op.batch_alter_table('player_provider_ids', schema=None) as batch_op:
        batch_op.create_index('ix_player_provider_ids_player', ['player_id', 'provider_key'], unique=False)

    op.create_table('player_season_eligibility',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('nfl_team_id', sa.String(length=32), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_team_id'], ['nfl_teams.id'], name=op.f('fk_player_season_eligibility_nfl_team_id_nfl_teams')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_season_eligibility_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_season_eligibility')),
    sa.UniqueConstraint('player_id', 'season', 'effective_at', name='uq_player_season_eligibility_player_id')
    )
    with op.batch_alter_table('player_season_eligibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_eligibility_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_eligibility_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_eligibility_provider_id'), ['provider_id'], unique=False)

    op.create_table('player_status_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('designation', sa.String(length=24), nullable=True),
    sa.Column('body_part', sa.String(length=48), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_status_events_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_status_events'))
    )
    with op.batch_alter_table('player_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_status_events_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index('ix_player_status_events_player_eff', ['player_id', 'effective_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_status_events_provider_id'), ['provider_id'], unique=False)

    op.create_table('projections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('stat_line', sa.JSON(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('floor_points', sa.Float(), nullable=True),
    sa.Column('ceiling_points', sa.Float(), nullable=True),
    sa.Column('stdev_points', sa.Float(), nullable=True),
    sa.Column('games_remaining', sa.Integer(), nullable=True),
    sa.Column('scoring_ruleset', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_projections_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projections')),
    sa.UniqueConstraint('player_id', 'season', 'week', 'scope', 'provider_id', 'retrieved_at', name='uq_projections_player_id')
    )
    with op.batch_alter_table('projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projections_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index('ix_projections_lookup', ['season', 'week', 'scope', 'player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projections_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projections_provider_id'), ['provider_id'], unique=False)

    op.create_table('pulse_acknowledgements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_through', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_pulse_acknowledgements_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pulse_acknowledgements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_acknowledgements'))
    )
    with op.batch_alter_table('pulse_acknowledgements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pulse_acknowledgements_league_season_id'), ['league_season_id'], unique=False)

    op.create_table('rankings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('expert_consensus_stdev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_rankings_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rankings')),
    sa.UniqueConstraint('player_id', 'season', 'week', 'scope', 'provider_id', 'retrieved_at', name='uq_rankings_player_id')
    )
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rankings_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_provider_id'), ['provider_id'], unique=False)

    op.create_table('standings_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('standings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_standings_snapshots_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings_snapshots'))
    )
    with op.batch_alter_table('standings_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_snapshots_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('team_seasons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('draft_position', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Float(), nullable=False),
    sa.Column('points_against', sa.Float(), nullable=False),
    sa.Column('faab_remaining', sa.Integer(), nullable=True),
    sa.Column('waiver_priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_team_seasons_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_seasons_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_seasons')),
    sa.UniqueConstraint('team_id', 'league_season_id', name='uq_team_seasons_team_id')
    )
    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_seasons_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_seasons_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_seasons_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_seasons_team_id'), ['team_id'], unique=False)

    op.create_table('tiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('tier_label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_tiers_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiers')),
    sa.UniqueConstraint('player_id', 'season', 'week', 'provider_id', 'retrieved_at', name='uq_tiers_player_id')
    )
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiers_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiers_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiers_provider_id'), ['provider_id'], unique=False)

    op.create_table('usage_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('snap_pct', sa.Float(), nullable=True),
    sa.Column('route_pct', sa.Float(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('carry_share', sa.Float(), nullable=True),
    sa.Column('red_zone_touches', sa.Integer(), nullable=True),
    sa.Column('air_yards_share', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_usage_snapshots_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_snapshots')),
    sa.UniqueConstraint('player_id', 'season', 'week', 'provider_id', name='uq_usage_snapshots_player_id')
    )
    with op.batch_alter_table('usage_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_snapshots_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('waiver_state_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('next_process_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_waiver_state_snapshots_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waiver_state_snapshots'))
    )
    with op.batch_alter_table('waiver_state_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_state_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_state_snapshots_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_state_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('weather_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nfl_game_id', sa.String(length=32), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('precipitation_chance', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nfl_game_id'], ['nfl_games.id'], name=op.f('fk_weather_snapshots_nfl_game_id_nfl_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_snapshots'))
    )
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_snapshots_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_nfl_game_id'), ['nfl_game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_provider_id'), ['provider_id'], unique=False)

    op.create_table('draft_slots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('overall_pick', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_in_round', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=False),
    sa.Column('is_keeper_slot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_slots_draft_id_drafts')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_draft_slots_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_slots')),
    sa.UniqueConstraint('draft_id', 'overall_pick', name='uq_draft_slots_draft_id')
    )
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_slots_draft_id'), ['draft_id'], unique=False)

    op.create_table('draft_state_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_state_versions_draft_id_drafts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_state_versions')),
    sa.UniqueConstraint('draft_id', 'version', name='uq_draft_state_versions_draft_id')
    )
    with op.batch_alter_table('draft_state_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_state_versions_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_state_versions_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('matchups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_season_id', sa.String(length=32), nullable=False),
    sa.Column('away_team_season_id', sa.String(length=32), nullable=True),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_season_id'], ['team_seasons.id'], name=op.f('fk_matchups_away_team_season_id_team_seasons')),
    sa.ForeignKeyConstraint(['home_team_season_id'], ['team_seasons.id'], name=op.f('fk_matchups_home_team_season_id_team_seasons')),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_matchups_league_season_id_league_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matchups')),
    sa.UniqueConstraint('league_season_id', 'week', 'home_team_season_id', name='uq_matchups_league_season_id')
    )
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchups_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchups_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchups_provider_id'), ['provider_id'], unique=False)

    op.create_table('pulse_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=True),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_pulse_runs_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['decision_snapshots.id'], name=op.f('fk_pulse_runs_snapshot_id_decision_snapshots')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_pulse_runs_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_runs'))
    )
    op.create_table('recommendation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('command', sa.String(length=24), nullable=False),
    sa.Column('subcommand', sa.String(length=32), nullable=True),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=True),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_status', sa.String(length=16), nullable=False),
    sa.Column('degraded_reasons', sa.JSON(), nullable=False),
    sa.Column('check_again_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('explanation_model', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_recommendation_runs_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['decision_snapshots.id'], name=op.f('fk_recommendation_runs_snapshot_id_decision_snapshots')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_recommendation_runs_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_runs'))
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_recommendation_runs_cmd_time', ['command', 'generated_at'], unique=False)

    op.create_table('roster_memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=True),
    sa.Column('acquisition_type', sa.String(length=24), nullable=True),
    sa.Column('acquisition_cost', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_roster_memberships_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_roster_memberships_player_id_players')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_roster_memberships_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_memberships'))
    )
    with op.batch_alter_table('roster_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_roster_memberships_current', ['league_season_id', 'player_id', 'ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_memberships_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_memberships_league_season_id'), ['league_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_memberships_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_memberships_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_memberships_team_season_id'), ['team_season_id'], unique=False)

    op.create_table('roster_slots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_rules_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('eligible_positions', sa.JSON(), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_rules_id'], ['league_rules.id'], name=op.f('fk_roster_slots_league_rules_id_league_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_slots')),
    sa.UniqueConstraint('league_rules_id', 'slot', 'ordinal', name='uq_roster_slots_league_rules_id')
    )
    with op.batch_alter_table('roster_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roster_slots_league_rules_id'), ['league_rules_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=96), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=True),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_transactions_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_transactions_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('provider_key', 'external_id', name='uq_transactions_provider_key')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_transactions_season_time', ['league_season_id', 'processed_at'], unique=False)

    op.create_table('draft_picks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('draft_slot_id', sa.String(length=32), nullable=True),
    sa.Column('overall_pick', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('auction_price', sa.Integer(), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_picks_draft_id_drafts')),
    sa.ForeignKeyConstraint(['draft_slot_id'], ['draft_slots.id'], name=op.f('fk_draft_picks_draft_slot_id_draft_slots')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_draft_picks_player_id_players')),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], name=op.f('fk_draft_picks_team_season_id_team_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_picks')),
    sa.UniqueConstraint('draft_id', 'overall_pick', 'version', name='uq_draft_picks_draft_id')
    )
    with op.batch_alter_table('draft_picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_picks_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_picks_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_picks_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_picks_provider_id'), ['provider_id'], unique=False)

    op.create_table('pulse_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pulse_run_id', sa.String(length=32), nullable=False),
    sa.Column('league_season_id', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('deeper_command', sa.String(length=64), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('materiality_score', sa.Float(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], name=op.f('fk_pulse_items_league_season_id_league_seasons')),
    sa.ForeignKeyConstraint(['pulse_run_id'], ['pulse_runs.id'], name=op.f('fk_pulse_items_pulse_run_id_pulse_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pulse_items')),
    sa.UniqueConstraint('league_season_id', 'dedup_key', name='uq_pulse_items_league_season_id')
    )
    with op.batch_alter_table('pulse_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pulse_items_pulse_run_id'), ['pulse_run_id'], unique=False)

    op.create_table('recommendation_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('floor_points', sa.Float(), nullable=True),
    sa.Column('ceiling_points', sa.Float(), nullable=True),
    sa.Column('value_over_replacement', sa.Float(), nullable=True),
    sa.Column('survival_probability', sa.Float(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], name=op.f('fk_recommendation_candidates_run_id_recommendation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_candidates')),
    sa.UniqueConstraint('run_id', 'rank', name='uq_recommendation_candidates_run_id')
    )
    with op.batch_alter_table('recommendation_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_candidates_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_candidates_run_id'))

    op.drop_table('recommendation_candidates')
    with op.batch_alter_table('pulse_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pulse_items_pulse_run_id'))

    op.drop_table('pulse_items')
    with op.batch_alter_table('draft_picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_picks_provider_id'))
        batch_op.drop_index(batch_op.f('ix_draft_picks_player_id'))
        batch_op.drop_index(batch_op.f('ix_draft_picks_ingestion_run_id'))
        batch_op.drop_index(batch_op.f('ix_draft_picks_draft_id'))

    op.drop_table('draft_picks')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_season_time')
        batch_op.drop_index(batch_op.f('ix_transactions_provider_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_ingestion_run_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('roster_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_slots_league_rules_id'))

    op.drop_table('roster_slots')
    with op.batch_alter_table('roster_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_memberships_team_season_id'))
        batch_op.drop_index(batch_op.f('ix_roster_memberships_provider_id'))
        batch_op.drop_index(batch_op.f('ix_roster_memberships_player_id'))
        batch_op.drop_index(batch_op.f('ix_roster_memberships_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_roster_memberships_ingestion_run_id'))
        batch_op.drop_index('ix_roster_memberships_current')

    op.drop_table('roster_memberships')
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendation_runs_cmd_time')

    op.drop_table('recommendation_runs')
    op.drop_table('pulse_runs')
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchups_provider_id'))
        batch_op.drop_index(batch_op.f('ix_matchups_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_matchups_ingestion_run_id'))

    op.drop_table('matchups')
    with op.batch_alter_table('draft_state_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_state_versions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_draft_state_versions_draft_id'))

    op.drop_table('draft_state_versions')
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_slots_draft_id'))

    op.drop_table('draft_slots')
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_nfl_game_id'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_ingestion_run_id'))

    op.drop_table('weather_snapshots')
    with op.batch_alter_table('waiver_state_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_state_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_state_snapshots_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_state_snapshots_ingestion_run_id'))

    op.drop_table('waiver_state_snapshots')
    with op.batch_alter_table('usage_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_usage_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_usage_snapshots_ingestion_run_id'))

    op.drop_table('usage_snapshots')
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiers_provider_id'))
        batch_op.drop_index(batch_op.f('ix_tiers_player_id'))
        batch_op.drop_index(batch_op.f('ix_tiers_ingestion_run_id'))

    op.drop_table('tiers')
    with op.batch_alter_table('team_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_seasons_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_seasons_provider_id'))
        batch_op.drop_index(batch_op.f('ix_team_seasons_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_team_seasons_ingestion_run_id'))

    op.drop_table('team_seasons')
    with op.batch_alter_table('standings_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_standings_snapshots_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_standings_snapshots_ingestion_run_id'))

    op.drop_table('standings_snapshots')
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rankings_provider_id'))
        batch_op.drop_index(batch_op.f('ix_rankings_player_id'))
        batch_op.drop_index(batch_op.f('ix_rankings_ingestion_run_id'))

    op.drop_table('rankings')
    with op.batch_alter_table('pulse_acknowledgements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pulse_acknowledgements_league_season_id'))

    op.drop_table('pulse_acknowledgements')
    with op.batch_alter_table('projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projections_provider_id'))
        batch_op.drop_index(batch_op.f('ix_projections_player_id'))
        batch_op.drop_index('ix_projections_lookup')
        batch_op.drop_index(batch_op.f('ix_projections_ingestion_run_id'))

    op.drop_table('projections')
    with op.batch_alter_table('player_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_status_events_provider_id'))
        batch_op.drop_index('ix_player_status_events_player_eff')
        batch_op.drop_index(batch_op.f('ix_player_status_events_ingestion_run_id'))

    op.drop_table('player_status_events')
    with op.batch_alter_table('player_season_eligibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_season_eligibility_provider_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_eligibility_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_eligibility_ingestion_run_id'))

    op.drop_table('player_season_eligibility')
    with op.batch_alter_table('player_provider_ids', schema=None) as batch_op:
        batch_op.drop_index('ix_player_provider_ids_player')

    op.drop_table('player_provider_ids')
    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_aliases_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_aliases_normalized_alias'))

    op.drop_table('player_aliases')
    with op.batch_alter_table('market_trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_trends_provider_id'))
        batch_op.drop_index(batch_op.f('ix_market_trends_player_id'))
        batch_op.drop_index(batch_op.f('ix_market_trends_ingestion_run_id'))

    op.drop_table('market_trends')
    with op.batch_alter_table('market_context_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_context_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_market_context_snapshots_nfl_game_id'))
        batch_op.drop_index(batch_op.f('ix_market_context_snapshots_ingestion_run_id'))

    op.drop_table('market_context_snapshots')
    with op.batch_alter_table('league_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_rules_provider_id'))
        batch_op.drop_index(batch_op.f('ix_league_rules_league_season_id'))
        batch_op.drop_index(batch_op.f('ix_league_rules_ingestion_run_id'))

    op.drop_table('league_rules')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_provider_id'))
        batch_op.drop_index(batch_op.f('ix_drafts_ingestion_run_id'))

    op.drop_table('drafts')
    with op.batch_alter_table('depth_chart_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_depth_chart_snapshots_team_eff')
        batch_op.drop_index(batch_op.f('ix_depth_chart_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_depth_chart_snapshots_ingestion_run_id'))

    op.drop_table('depth_chart_snapshots')
    with op.batch_alter_table('decision_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_snapshots_league_time')
        batch_op.drop_index(batch_op.f('ix_decision_snapshots_content_hash'))

    op.drop_table('decision_snapshots')
    with op.batch_alter_table('adp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_provider_id'))
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_ingestion_run_id'))

    op.drop_table('adp_snapshots')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_league_id'))

    op.drop_table('teams')
    with op.batch_alter_table('source_freshness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_freshness_provider_id'))

    op.drop_table('source_freshness')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_provider_id'))
        batch_op.drop_index('ix_players_normalized_name')
        batch_op.drop_index(batch_op.f('ix_players_ingestion_run_id'))

    op.drop_table('players')
    with op.batch_alter_table('nfl_games', schema=None) as batch_op:
        batch_op.drop_index('ix_nfl_games_season_week')
        batch_op.drop_index(batch_op.f('ix_nfl_games_provider_id'))
        batch_op.drop_index(batch_op.f('ix_nfl_games_ingestion_run_id'))

    op.drop_table('nfl_games')
    with op.batch_alter_table('league_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_seasons_provider_id'))
        batch_op.drop_index(batch_op.f('ix_league_seasons_league_id'))
        batch_op.drop_index(batch_op.f('ix_league_seasons_ingestion_run_id'))

    op.drop_table('league_seasons')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_capability'))

    op.drop_table('ingestion_runs')
    op.drop_table('users')
    op.drop_table('source_providers')
    op.drop_table('nfl_teams')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_provider_id'))
        batch_op.drop_index(batch_op.f('ix_news_items_ingestion_run_id'))

    op.drop_table('news_items')
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_overrides_entity_id'))

    op.drop_table('manual_overrides')
    op.drop_table('leagues')
    # ### end Alembic commands ###
