"""initial schema

Revision ID: 32e7cf2d3968
Revises: 
Create Date: 2026-09-02 02:30:13.259080
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '32e7cf2d3968'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('yoto_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('publish_hour', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('listener_age', sa.Integer(), nullable=False),
    sa.Column('nova_voice_id', sa.String(length=64), nullable=True),
    sa.Column('rae_voice_id', sa.String(length=64), nullable=True),
    sa.Column('audio_pipeline', sa.String(length=16), nullable=True),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families')),
    sa.UniqueConstraint('yoto_user_id', name='uq_families_yoto_user_id')
    )
    op.create_table('manual_overrides',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_table', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_overrides'))
    )
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_overrides_entity_id'), ['entity_id'], unique=False)

    op.create_table('news_stories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('story_type', sa.String(length=48), nullable=True),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('team_external_ids', sa.JSON(), nullable=False),
    sa.Column('safety_verdict', sa.String(length=8), nullable=False),
    sa.Column('safety_category', sa.String(length=48), nullable=True),
    sa.Column('safety_matched', sa.String(length=120), nullable=True),
    sa.Column('caution', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_stories')),
    sa.UniqueConstraint('league_key', 'external_id', name='uq_news_stories_league_key')
    )
    with op.batch_alter_table('news_stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_stories_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_stories_league_key'), ['league_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_stories_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_news_stories_published', ['published_at'], unique=False)
        batch_op.create_index('ix_news_stories_verdict', ['safety_verdict'], unique=False)

    op.create_table('oauth_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('next_path', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_transactions')),
    sa.UniqueConstraint('state', name='uq_oauth_transactions_state')
    )
    op.create_table('source_providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('freshness_class', sa.String(length=16), nullable=False),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('raw_retention_days', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_providers')),
    sa.UniqueConstraint('key', name='uq_source_providers_key')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=96), nullable=False),
    sa.Column('location', sa.String(length=96), nullable=True),
    sa.Column('abbreviation', sa.String(length=12), nullable=True),
    sa.Column('search_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('logo_url', sa.String(length=600), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('record_summary', sa.String(length=64), nullable=True),
    sa.Column('standing_summary', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('league_key', 'external_id', name='uq_teams_league_key')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_league_key'), ['league_key'], unique=False)
        batch_op.create_index('ix_teams_league_search', ['league_key', 'search_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_provider_id'), ['provider_id'], unique=False)

    op.create_table('athletes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('jersey', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=160), nullable=True),
    sa.Column('headshot_url', sa.String(length=600), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_athletes_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athletes')),
    sa.UniqueConstraint('league_key', 'external_id', name='uq_athletes_league_key')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index('ix_athletes_birthday', ['birth_month', 'birth_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_league_key'), ['league_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_team_id'), ['team_id'], unique=False)

    op.create_table('favorite_teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_favorite_teams_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_favorite_teams_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_teams')),
    sa.UniqueConstraint('family_id', 'team_id', name='uq_favorite_teams_family_id')
    )
    with op.batch_alter_table('favorite_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_teams_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_teams_team_id'), ['team_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('status_detail', sa.String(length=200), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('home_team_id', sa.String(length=32), nullable=True),
    sa.Column('away_team_id', sa.String(length=32), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('broadcast', sa.String(length=120), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_games_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_games_home_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('league_key', 'external_id', name='uq_games_league_key')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_away', ['away_team_id', 'start_at'], unique=False)
        batch_op.create_index('ix_games_home', ['home_team_id', 'start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_league_key'), ['league_key'], unique=False)
        batch_op.create_index('ix_games_league_start', ['league_key', 'start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_state'), ['state'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['source_providers.id'], name=op.f('fk_ingestion_runs_provider_id_source_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_ingestion_runs_idempotency_key')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_provider_id'), ['provider_id'], unique=False)

    op.create_table('show_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('calculation_version', sa.String(length=32), nullable=False),
    sa.Column('audio_pipeline', sa.String(length=16), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('brief_hash', sa.String(length=64), nullable=True),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('labs_job_id', sa.String(length=64), nullable=True),
    sa.Column('estimated_minutes', sa.Float(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('blocked_stories', sa.JSON(), nullable=False),
    sa.Column('narration_used', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_show_runs_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_runs')),
    sa.UniqueConstraint('family_id', 'show_date', name='uq_show_runs_family_id')
    )
    with op.batch_alter_table('show_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_show_runs_brief_hash'), ['brief_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_show_runs_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_show_runs_status', ['status'], unique=False)

    op.create_table('source_freshness',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('freshness_class', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingestion_run_id', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['source_providers.id'], name=op.f('fk_source_freshness_provider_id_source_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_freshness')),
    sa.UniqueConstraint('provider_id', 'capability', 'scope', name='uq_source_freshness_provider_id')
    )
    with op.batch_alter_table('source_freshness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_freshness_provider_id'), ['provider_id'], unique=False)

    op.create_table('yoto_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_yoto_credentials_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yoto_credentials')),
    sa.UniqueConstraint('family_id', name='uq_yoto_credentials_family_id')
    )
    op.create_table('show_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('track_key', sa.String(length=8), nullable=False),
    sa.Column('chapter_key', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('source_script', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('audio_sha256', sa.String(length=128), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('audio_format', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('material_inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['show_runs.id'], name=op.f('fk_show_segments_run_id_show_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_segments')),
    sa.UniqueConstraint('run_id', 'track_key', 'chapter_key', name='uq_show_segments_run_id')
    )
    with op.batch_alter_table('show_segments', schema=None) as batch_op:
        batch_op.create_index('ix_show_segments_run_order', ['run_id', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_show_segments_run_order')

    op.drop_table('show_segments')
    op.drop_table('yoto_credentials')
    with op.batch_alter_table('source_freshness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_freshness_provider_id'))

    op.drop_table('source_freshness')
    with op.batch_alter_table('show_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_show_runs_status')
        batch_op.drop_index(batch_op.f('ix_show_runs_family_id'))
        batch_op.drop_index(batch_op.f('ix_show_runs_brief_hash'))

    op.drop_table('show_runs')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_capability'))

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_state'))
        batch_op.drop_index(batch_op.f('ix_games_provider_id'))
        batch_op.drop_index('ix_games_league_start')
        batch_op.drop_index(batch_op.f('ix_games_league_key'))
        batch_op.drop_index(batch_op.f('ix_games_ingestion_run_id'))
        batch_op.drop_index('ix_games_home')
        batch_op.drop_index('ix_games_away')

    op.drop_table('games')
    with op.batch_alter_table('favorite_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_teams_family_id'))

    op.drop_table('favorite_teams')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_team_id'))
        batch_op.drop_index(batch_op.f('ix_athletes_provider_id'))
        batch_op.drop_index(batch_op.f('ix_athletes_league_key'))
        batch_op.drop_index(batch_op.f('ix_athletes_ingestion_run_id'))
        batch_op.drop_index('ix_athletes_birthday')

    op.drop_table('athletes')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_provider_id'))
        batch_op.drop_index('ix_teams_league_search')
        batch_op.drop_index(batch_op.f('ix_teams_league_key'))
        batch_op.drop_index(batch_op.f('ix_teams_ingestion_run_id'))

    op.drop_table('teams')
    op.drop_table('source_providers')
    op.drop_table('oauth_transactions')
    with op.batch_alter_table('news_stories', schema=None) as batch_op:
        batch_op.drop_index('ix_news_stories_verdict')
        batch_op.drop_index('ix_news_stories_published')
        batch_op.drop_index(batch_op.f('ix_news_stories_provider_id'))
        batch_op.drop_index(batch_op.f('ix_news_stories_league_key'))
        batch_op.drop_index(batch_op.f('ix_news_stories_ingestion_run_id'))

    op.drop_table('news_stories')
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_overrides_entity_id'))

    op.drop_table('manual_overrides')
    op.drop_table('families')
    # ### end Alembic commands ###
